# Actividad 1. Introducción a Pandas 
Con el fichero Fichero `sample_NYC_parking_issues.csv`

Indica tu nombre, también aquí:

<hr/>

```text
Name: David Prokes
```

<hr/>

In [1]:
# Cargamos el paquete de pandas:
import pandas as pd

In [2]:
# Cargamos el fichero de datos, con la peculiaridad que se emplea como separador ";".
df = pd.read_csv("Datos/sample_NYC_parking_issues.csv", sep = ";")

# Visualizamos los datos para comprobar que mantiene una estructura coherente:
df.head()

,Unnamed: 0,Summons Number,Plate ID,Registration State,Plate Type,Issue Date,Violation Code,Vehicle Body Type,Vehicle Make,Issuing Agency,...,Vehicle Color,Unregistered Vehicle?,Vehicle Year,Meter Number,Feet From Curb,Violation Post Code,Violation Description,No Standing or Stopping Violation,Hydrant Violation,Double Parking Violation
0,7192124,7684215310,24824MD,NY,COM,04/23/2014,71,VAN,FRIG,T,...,WH,NaN,2004.0,NaN,0.0,01 4,71A-Insp Sticker Expired (NYS),NaN,NaN,NaN
1,1399831,5070680213,9TOPCLAS,NY,OMT,09/14/2013,7,4DSD,DODGE,V,...,BK,NaN,2008.0,NaN,0.0,NaN,FAILURE TO STOP AT RED LIGHT,NaN,NaN,NaN
2,5369188,1356951855,GEL1573,NY,PAS,02/13/2014,71,SUBN,HONDA,P,...,NaN,0.0,2006.0,-,0.0,NaN,NaN,NaN,NaN,NaN
3,6338606,7713806271,EDU1026,NY,PAS,03/20/2014,21,SUBN,TOYOT,T,...,GY,NaN,2008.0,NaN,0.0,14 4,21-No Parking (street clean),NaN,NaN,NaN
4,2823881,7645478044,DXX6460,NY,PAS,11/01/2013,20,4DSD,HONDA,T,...,MR,NaN,1996.0,NaN,0.0,03-A,20A-No Parking (Non-COM),NaN,NaN,NaN


#### A, ¿Qué columnas no aportan ningún valor a las muestras?

In [3]:
# Primeramente observamos de cuantas filas se compone el dataframe:
df.shape

# Ahora filtramos aquellas columnas con todos los valores NaN y vemos que las 3 últimas columnas en concreto se encuentran vacías:
df.isna().all()

# Por lo que, al tener la misma longitud que las columnas, lo aplicamos y obtenemos el vector con las columnas que no aportan ningún valor:
df.columns[df.isna().all()]

Index(['No Standing or Stopping Violation', 'Hydrant Violation',
       'Double Parking Violation'],
      dtype='object')

####  B. Selecciona las muestras "4DSD" en `Vehicle Body Type`  y guardalas en un nuevo fichero

In [4]:
# Filtramos la columna por el string indicado y lo indexamos de nuevo en el dataframe, guardándolo como un nuevo df:
df2 = df[df["Vehicle Body Type"] == "4DSD"]

# Exportamos como un nuevo fichero csv el dataframe filtrado:
df2.to_csv("Datos/Vehicle Body Type.csv")

#### C. ¿Cuántos colores de vehículos hay?

In [5]:
# A continuación aplicamos el método value_counts() para agrupar por valores únicos y medimos la longitud de la serie, dando el total de colores:
count_colores = len(df["Vehicle Color"].value_counts())

print("El total de colores registrados es de " + str(count_colores))

El total de colores registrados es de 106

#### D. ¿Cuál es el rango de años en la antigüedad del vehículo?

In [6]:
# Suponemos que la antigüedad viene dada en la columna del año del vehículo, por lo que buscamos el año máximo y el mínimo:
minimo = df["Vehicle Year"].min()
maximo = df["Vehicle Year"].max()

print("El rango de años dado es de " + str(int(minimo)) + "-" + str(int(maximo)))

El rango de años dado es de 0-2069

#### E. ¿Cuál es el tipo de vehículo más viejo?

In [7]:
# Filtramos los datos por el valor mínimo encontrado anteriormente, escogemos la columna, aplicamos value_counts:
df[df["Vehicle Year"] == minimo]["Vehicle Body Type"].value_counts()

# Vemos que existen varios tipos de vehículos que cumplen la condición de tener una antigüedad igual a la mínima, por lo que el criterio para
# decidir que vehículo es el más viejo será escoger el que mayor número de ellos tiene registrados:
mas_antiguo = df[df["Vehicle Year"] == minimo]["Vehicle Body Type"].value_counts().index[0]

print("El tipo de vehículo con un mayor número de registros en el año mínimo es " + str(mas_antiguo))

El tipo de vehículo con un mayor número de registros en el año mínimo es 4DSD

####  F. ¿Cuál es la distancia mínima del vehículo a la acera "Feet From Curb"?

In [8]:
# Del enunciado entiendo que simplemente hay que encontrar el valor mínimo en la columna indicada:
df["Feet From Curb"].min()

0.0

####  G. Selecciona aquellas muestras que estén por debajo de la distancia `Feet From Curb` media

In [9]:
# Primero calculamos la distancia media de la columna indicada:
media = df["Feet From Curb"].mean()

# Ahora filtramos aquellas filas cuya distancia en la columna indicada es estrictamente menor a la media:
df[df["Feet From Curb"] < media]

,Unnamed: 0,Summons Number,Plate ID,Registration State,Plate Type,Issue Date,Violation Code,Vehicle Body Type,Vehicle Make,Issuing Agency,...,Vehicle Color,Unregistered Vehicle?,Vehicle Year,Meter Number,Feet From Curb,Violation Post Code,Violation Description,No Standing or Stopping Violation,Hydrant Violation,Double Parking Violation
0,7192124,7684215310,24824MD,NY,COM,04/23/2014,71,VAN,FRIG,T,...,WH,NaN,2004.0,NaN,0.0,01 4,71A-Insp Sticker Expired (NYS),NaN,NaN,NaN
1,1399831,5070680213,9TOPCLAS,NY,OMT,09/14/2013,7,4DSD,DODGE,V,...,BK,NaN,2008.0,NaN,0.0,NaN,FAILURE TO STOP AT RED LIGHT,NaN,NaN,NaN
2,5369188,1356951855,GEL1573,NY,PAS,02/13/2014,71,SUBN,HONDA,P,...,NaN,0.0,2006.0,-,0.0,NaN,NaN,NaN,NaN,NaN
3,6338606,7713806271,EDU1026,NY,PAS,03/20/2014,21,SUBN,TOYOT,T,...,GY,NaN,2008.0,NaN,0.0,14 4,21-No Parking (street clean),NaN,NaN,NaN
4,2823881,7645478044,DXX6460,NY,PAS,11/01/2013,20,4DSD,HONDA,T,...,MR,NaN,1996.0,NaN,0.0,03-A,20A-No Parking (Non-COM),NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,51871,1359994981,42799JW,NY,COM,07/24/2013,14,VAN,FRG,P,...,WHIT,0.0,2007.0,-,0.0,NaN,NaN,NaN,NaN,NaN
9996,2178598,7531580299,BLANKPLATE,99,999,10/10/2013,21,MCY,TRIUM,T,...,BLACK,NaN,0.0,NaN,0.0,01 -,21-No Parking (street clean),NaN,NaN,NaN
9997,5536586,1353773541,FXW2962,NY,PAS,02/21/2014,16,SDN,MAZDA,T,...,GR,0.0,1996.0,-,0.0,NaN,NaN,NaN,NaN,NaN
9998,1127482,7207594008,CLR2162,NY,PAS,09/05/2013,37,4DSD,HONDA,T,...,SILVE,NaN,2006.0,495-0067,0.0,52-P,37-Expired Muni Meter,NaN,NaN,NaN
9999,2822344,7536561775,DJG9703,NY,PAS,11/01/2013,46,SUBN,HONDA,T,...,BLACK,NaN,2005.0,NaN,0.0,06 -,46A-Double Parking (Non-COM),NaN,NaN,NaN

####  H. Elimina las dos últimas columnas del dataframe creando uno nuevo.

In [10]:
# Podemos eliminar las dos últimas columnas a partir de un slicing:
df3 = df.iloc[:,:-2]

#### I. Selecciona la 4º, 6º y 8º columna de las filas comprendidas entre la 1 y 100, y la 200 y 500.

In [11]:
# Al empezar los índices en 0, seleccionamos las columnas con el índice i-1, ya que la cuarta columna en realidad sería aquella cuyo índice
# es 3. Mientras que, las filas sería lo mismo, seleccionando el índice i-1:
c1 = df.iloc[0:100,[3,5,7]]
c2 = df.iloc[199:500,[3,5,7]]

# Ahora concatenamos ambos rangos de filas:
df4 = pd.concat([c1,c2])

#### J. ¿Hay vehículos que han recibido más de una multa ?

In [12]:
repetidores = len(df["Plate ID"].value_counts() > 1)

print("Sí, en concreto del total de 10000 registros, " + str(repetidores) + " matrículas se repiten como mínimo más de una vez")

Sí, en concreto del total de 10000 registros, 9804 matrículas se repiten como mínimo más de una vez

####  K. Los nombres de los propietarios (nombres ficticios) están en otro fichero (`plates_properties.csv`), combina ambos ficheros con coherencia en relación a la informació y guarda el resultado en otro documento csv.

In [14]:
df_merge = pd.read_csv("Datos/plates_properties.csv", index_col=0)

# Creamos un merge left, donde queremos mantener los datos del dataframe trabajado, sumado a los nombres de correspondientes a las matrículas
# de coche que se tienen.
df5 = df.merge(df_merge, left_on="Plate ID", right_on="plate_id", how="left")

# Guardamos en un archivo csv:
df5.to_csv("Datos/Ejercicio K.csv")